# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_mails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='category',
            field=models.CharField(default='-1', max_length=10),
        ),
    ]
