# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_mails_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='sender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mails',
            name='snippet',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mails',
            name='subject',
            field=models.CharField(default='', max_length=250),
        ),
    ]
